# Site settings
title: Divertons
email: contato@divertons.com.br
url: http://divertons.com.br
description: "Diversos tons para todos os momentos!"
keywords: "design, design grafico, custom avatar, artesanal"
skills: "Diversos tons para todos os momentos!"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: divertons

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: cdb2df #e34f9c #e31881
  primary-rgb: "205,178,223" #"227,79,156"
  secondary: e31881 #582a77 #490677
  secondary-dark: 490677

# Footer settings
footer:
  social: Redes Sociais

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/divertons
  - title: instagram
    url: https://instagram.com/divertons
  - title: pinterest
    url: https://pinterest.com/divertons
  - title: envelope
    url: mailto:contato@divertons.com.br
  - title: shopping-cart
    url: https://loja.divertons.com.br

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
